/* Chax Training: small, dependency-free, offline first training companion. */
const $=s=>document.querySelector(s), app=$('#app'), overlay=$('#overlay');
const days=[
 {label:'Mon',title:'PUSH',key:'Day 1 · Push',rest:false},
 {label:'Tue',title:'PULL',key:'Day 2 · Pull',rest:false},
 {label:'Wed',title:'REST DAY',key:'rest-wed',rest:true},
 {label:'Thu',title:'LOWER A',key:'Day 4 · Lower A',rest:false},
 {label:'Fri',title:'UPPER',key:'Day 5 · Upper',rest:false},
 {label:'Sat',title:'LOWER B + CORE',key:'Day 6 · Lower B + Core',rest:false},
 {label:'Sun',title:'REST DAY',key:'rest-sun',rest:true}
];
const defaults={settings:{sound:true,vibrate:true,autoStart:true,theme:'dark',language:'en'},history:[],bodyweight:[],swaps:{}};
function read(){try{return {...defaults,...JSON.parse(localStorage.getItem('iron-data')||'{}')}}catch(e){return structuredClone(defaults)}}
let state=read(), workout=null, timer=null, wake=null, selectedDay=todayIndex(), currentPage='home', sessionClock=null;
function save(){try{localStorage.setItem('iron-data',JSON.stringify(state))}catch(e){toast('Could not save data on this device')}}
function todayIndex(){return (new Date().getDay()+6)%7}
function exForDay(day){return window.WORKOUT_DATA.filter(x=>x.day===days[day].key)}
function titleCase(s){return s.replace(/\b\w/g,x=>x.toUpperCase())}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function estimate(ex){let n=0;ex.forEach(x=>n+=x.sets*(x.rest+38));return Math.max(20,Math.round(n/60+ex.length*1.2))}
function latestSession(day){return [...state.history].reverse().find(s=>s.day===days[day].title)}
function showHome(){currentPage='home';selectedDay=selectedDay??todayIndex();$('.bottom-nav').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===0));renderHome()}
function renderHome(){const d=days[selectedDay], ex=exForDay(selectedDay), last=latestSession(selectedDay);let cards=days.map((x,i)=>`<button class="day-chip ${i===selectedDay?'selected':''} ${state.history.some(s=>s.day===x.title)?'done':''}" onclick="selectDay(${i})"><span>${x.label}</span><strong>${x.rest?'·':String(i+1).padStart(2,'0')}</strong><span>${x.title.split(' ')[0]}</span></button>`).join('');
app.innerHTML=`<div class="container"><section class="hero"><div class="eyebrow">${new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase()}</div><h1>Your week,<br>one rep at a time.</h1><p>Five sessions. Two lower days. Room to grow.</p></section><div class="week">${cards}</div>${d.rest?restCard(d):`<section class="workout-card"><div class="workout-head"><div><div class="eyebrow">DAY ${selectedDay+1} · ${d.label.toUpperCase()}</div><h2>${d.title}</h2></div><span class="badge">${last?'LAST TRAINED':'TODAY'}</span></div><div class="stats"><div><b>${ex.length}</b> exercises</div><div><b>${estimate(ex)} min</b> estimated</div><div><b>${ex.reduce((a,x)=>a+x.sets,0)}</b> total sets</div></div><div class="exercise-list">${ex.map((x,i)=>`<div class="exercise-row"><span class="number">${String(i+1).padStart(2,'0')}</span><span>${esc(x.name)}<small>${x.sets} × ${esc(x.reps)} · ${targetLabel(x)}</small></span></div>`).join('')}</div><button class="primary full" onclick="warmup()">Start workout <span aria-hidden="true">→</span></button></section>`}<div class="section-title"><h2>Keep the streak easy</h2><span class="eyebrow">WEEK ${Math.floor(state.history.length/5)+1}</span></div><div class="grid2"><div class="small-card"><b>Next deload</b><span>${Math.max(0,6-Math.floor(state.history.length/30))} weeks of training</span></div><div class="small-card"><b>Recent sessions</b><span>${state.history.length} logged workout${state.history.length===1?'':'s'}</span></div></div></div>`}
function restCard(d){return `<section class="workout-card"><div class="eyebrow">RECOVERY DAY</div><h2>${d.title}</h2><p class="muted">Let your body adapt. Keep movement light and comfortable.</p><div class="cue">Suggestion: take an easy 20–30 minute walk at a conversational pace.</div><h3>Gentle stretch checklist</h3><div class="rest-check">${['Hip flexor stretch · 30 s each side','Hamstring stretch · 30 s each side','Chest opener · 30 s','Child’s pose · 30 s, only if comfortable'].map((x,i)=>`<label><input type="checkbox" id="stretch${i}"> ${x}</label><br>`).join('')}</div><button class="secondary full" onclick="showHistory()">View progress</button></section>`}
function targetLabel(e){return (e.target||[]).map(titleCase).join(' · ')||'Full body'}
function selectDay(i){selectedDay=i;renderHome()}
function warmup(){const d=days[selectedDay];if(d.rest)return;const ex=exForDay(selectedDay);workout={day:selectedDay,exercises:ex,idx:0,done:ex.map(()=>[]),values:ex.map(x=>previousSets(x)),start:Date.now(),elapsed:0};drawWarmup()}
function drawWarmup(){overlay.innerHTML=`<div class="drawer-backdrop" onclick="if(event.target===this)closeOverlay()"><section class="drawer modal-wrap"><div class="eyebrow">BEFORE YOU BEGIN</div><h2>Quick warm-up</h2><p class="muted">A little preparation helps you move well through the first working set.</p><label class="checkline"><input type="checkbox"> 5 minutes of easy cardio</label><label class="checkline"><input type="checkbox"> 1–2 ramp-up sets before the first lift</label><div class="modal-actions"><button class="primary full" onclick="beginWorkout()">Let’s train</button><button class="ghost full" onclick="closeOverlay()">Not now</button></div></section></div>`}
async function beginWorkout(){closeOverlay();currentPage='walk';$('.bottom-nav').classList.add('hidden');try{if('wakeLock'in navigator)wake=await navigator.wakeLock.request('screen')}catch(e){} renderWalk();if(sessionClock)clearInterval(sessionClock);sessionClock=setInterval(updateElapsed,1000)}
function updateElapsed(){const el=$('#elapsedClock');if(el&&workout){let s=Math.floor((Date.now()-workout.start)/1000);el.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}}
function renderWalk(){if(!workout)return;const i=workout.idx,base=workout.exercises[i],swap=window.WORKOUT_DATA.find(x=>x.name===state.swaps[base.id]),e=swap?{...base,name:swap.name,target:swap.target,secondary:swap.secondary,instructions:swap.instructions,images:swap.images,matchedName:swap.matchedName,matchType:swap.matchType}:base,done=workout.done[i],last=lastValues(base),cur=e.name,progression=shouldIncrease(base)&&!base.limitedLoad;const target=swap?`Swap · ${targetLabel(e)}`:targetLabel(e);let sets=Array.from({length:e.sets},(_,j)=>{const v=workout.values[i][j],loadInput=e.weightless?'':`<label>KG<input aria-label="Set ${j+1} weight in kilograms" type="number" inputmode="decimal" step="0.5" value="${esc(v.weight)}" oninput="setValue(${j},'weight',this.value)" onchange="setValue(${j},'weight',this.value)"></label>`;return `<div class="set ${done.includes(j)?'done':''} ${e.weightless?'set-time':''}"><button class="set-button" aria-label="Mark set ${j+1} ${done.includes(j)?'not done':'done'}" onclick="toggleSet(${j})">${done.includes(j)?'✓':'SET '+(j+1)}</button>${loadInput}<label>${e.weightless?'SECONDS':'REPS'}<input aria-label="Set ${j+1} ${e.weightless?'seconds':'reps'}" type="number" inputmode="numeric" value="${esc(v.reps)}" oninput="setValue(${j},'reps',this.value)" onchange="setValue(${j},'reps',this.value)"></label></div>`}).join('');
app.innerHTML=`<div class="container"><div class="walk-head"><div><div class="eyebrow">${days[workout.day].title} · EXERCISE ${i+1} OF ${workout.exercises.length} <span style="margin-left:8px">ELAPSED <b id="elapsedClock">00:00</b></span></div><h1>${esc(cur)}</h1></div><div class="walk-controls"><button class="secondary" aria-label="Open exercise overview" onclick="openOverview()">☷</button><button class="secondary" aria-label="Exit workout" onclick="confirmExit()">×</button></div></div><div class="progress-track"><i style="width:${((i+1)/workout.exercises.length)*100}%"></i></div><div class="exercise-meta"><span>${e.sets} sets × ${esc(e.reps)}${e.weightless?'':' reps'}</span><span>${e.rest}s rest</span><span>${esc(target)}</span></div><div class="photos">${e.images.map((src,j)=>`<figure><img src="${esc(src)}" alt="${esc(e.matchedName)} ${j===0?'starting':'ending'} position" loading="lazy"><figcaption>${j===0?'START':'FINISH'}</figcaption></figure>`).join('')}</div>${e.matchType==='EQUIVALENT'?`<div class="lower-note">Image guide: ${esc(e.matchedName)} (closest dataset match)</div>`:''}<div class="instruction-title">HOW TO</div><ol class="instructions">${(e.instructions||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="cue"><b>YOUR KEY CUE</b><br>${esc(e.cue)}</div>${isSensitive(e)?`<div class="lower-note">Stop if the discomfort turns sharp rather than muscular.${/romanian deadlift/i.test(e.name)?' Keep the RDL light.':''}</div>`:''}<div class="section-title"><h2>Working sets</h2><span class="eyebrow">TAP A CIRCLE WHEN DONE</span></div><div class="sets">${sets}</div><div class="last-line"><span>${progression?(base.weightless?'Progression: hit 45 seconds on every set — try 5 more seconds.':'Progression: top reps on all sets last time — add 2.5 kg.'):base.limitedLoad?'Keep the RDL light and controlled.':last?(base.weightless?`Last time: ${last.reps} seconds`:`Last time: ${last.weight||'bodyweight'} kg × ${last.reps}`):'No previous set logged'}</span><button class="quick ${(base.weightless||base.limitedLoad)?'hidden':''}" onclick="quickAdd()">+2.5 kg</button></div><div class="walker-footer"><button class="secondary" onclick="step(-1)" ${i===0?'disabled':''}>← Back</button><button class="primary" onclick="step(1)">${i===workout.exercises.length-1?'Finish workout':'Next exercise →'}</button></div><div class="section-title"><h2>Exercise tools</h2></div><div class="grid2"><button class="secondary" onclick="swapExercise()">⇄ Swap exercise</button><a class="secondary" style="text-align:center;text-decoration:none;display:grid;place-items:center" target="_blank" rel="noreferrer" href="https://www.youtube.com/results?search_query=${encodeURIComponent(cur+' exercise form')}">▶ Form videos</a></div></div>${timer?timerMarkup():''}`;
if(timer)tickTimer();updateElapsed()}
function isSensitive(e){return /Day 2 · Pull|Day 4 · Lower A|Day 6 · Lower B/.test(e.day)||(e.target||[]).some(m=>['lats','lower back','middle back'].includes(m))}
function lastValues(e){for(let si=state.history.length-1;si>=0;si--){let hit=state.history[si].exercises?.find(x=>x.id===e.id);if(hit?.sets?.length){const valid=hit.sets.filter(x=>x.weight||x.reps);if(valid.length)return valid.reduce((a,b)=>+b.weight>+a.weight?b:a,valid[0])}}return null}
function previousSets(e){for(let si=state.history.length-1;si>=0;si--){const hit=state.history[si].exercises?.find(x=>x.id===e.id);if(hit?.sets?.length)return Array.from({length:e.sets},(_,j)=>({weight:hit.sets[j]?.weight||'',reps:hit.sets[j]?.reps||''}))}return Array.from({length:e.sets},()=>({weight:'',reps:''}))}
function shouldIncrease(e){for(let si=state.history.length-1;si>=0;si--){const hit=state.history[si].exercises?.find(x=>x.id===e.id);if(!hit)continue;const top=+rangeTop(e.reps);return hit.sets.length>=e.sets&&hit.sets.slice(0,e.sets).every(s=>s.done&&+s.reps>=top)}return false}
function setValue(j,key,val){workout.values[workout.idx][j][key]=val}
function quickAdd(){if(workout.exercises[workout.idx].weightless||workout.exercises[workout.idx].limitedLoad)return;const last=lastValues(workout.exercises[workout.idx]);const current=workout.values[workout.idx].find(v=>v.weight)?.weight;const val=current?+current+2.5:(last?+last.weight+2.5:2.5);workout.values[workout.idx].forEach(v=>v.weight=val);renderWalk()}
function toggleSet(j){const arr=workout.done[workout.idx],at=arr.indexOf(j);if(at>=0){arr.splice(at,1);if(timer){clearInterval(timer.interval);timer=null}}else{arr.push(j);arr.sort();workout.values[workout.idx][j].reps ||= rangeTop(workout.exercises[workout.idx].reps);if(state.settings.autoStart){startTimer(workout.exercises[workout.idx].rest)}}renderWalk()}
function rangeTop(r){const m=String(r).match(/(\d+)\s*(?:-|–|to)\s*(\d+)/);return m?m[2]:(String(r).match(/\d+/)||[''])[0]}
function step(n){if(n>0&&workout.idx===workout.exercises.length-1){finishWorkout();return}workout.idx=Math.max(0,Math.min(workout.exercises.length-1,workout.idx+n));renderWalk()}
function openOverview(){overlay.innerHTML=`<div class="drawer-backdrop" onclick="if(event.target===this)closeOverlay()"><section class="drawer"><button class="ghost" onclick="closeOverlay()">Close</button><h2>Workout overview</h2>${workout.exercises.map((e,i)=>`<button type="button" class="drawer-item overview-item" aria-label="Jump to ${esc(state.swaps[e.id]||e.name)}" onclick="jumpTo(${i})"><span class="number">${i+1}</span>${esc(state.swaps[e.id]||e.name)}<span class="status">${workout.done[i].length}/${e.sets}</span></button>`).join('')}</section></div>`}
function jumpTo(i){workout.idx=i;closeOverlay();renderWalk()}
function swapExercise(){const e=workout.exercises[workout.idx],same=window.WORKOUT_DATA.filter(x=>x.id!==e.id&&x.target?.some(m=>e.target?.includes(m))).slice(0,3);const items=same.length?same:[...window.WORKOUT_DATA.filter(x=>x.id!==e.id)].slice(0,3);overlay.innerHTML=`<div class="drawer-backdrop" onclick="if(event.target===this)closeOverlay()"><section class="drawer"><button class="ghost" onclick="closeOverlay()">Close</button><h2>Swap exercise</h2><p class="muted">Alternatives matched by primary muscle group.</p>${items.map(x=>`<button class="drawer-item" style="width:100%;background:none;color:var(--text);text-align:left" onclick="applySwap('${e.id}','${x.id}')">⇄ ${esc(x.name)}<span class="status">${esc((x.target||[]).map(titleCase).join(', '))}</span></button>`).join('')}</section></div>`}
function applySwap(id,name){state.swaps[id]=window.WORKOUT_DATA.find(x=>x.id===name).name;save();closeOverlay();renderWalk()}
function startTimer(seconds){if(timer?.interval)clearInterval(timer.interval);timer={end:Date.now()+seconds*1000,initial:seconds,interval:null,done:false};tickTimer();timer.interval=setInterval(tickTimer,400)}
function adjustTimer(n){if(timer){timer.end+=n*1000;timer.end=Math.max(Date.now(),timer.end);tickTimer()}}
function skipTimer(){if(timer?.interval)clearInterval(timer.interval);timer=null;renderWalk()}
function timerMarkup(){const s=Math.max(0,Math.ceil((timer.end-Date.now())/1000));return `<div class="sticky-timer ${s===0?'timer-flash':''}" id="timerPanel"><div><div class="eyebrow">REST · ${s===0?'TIME':'REMAINING'}</div><strong>${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}</strong></div><div class="timer-actions"><button onclick="adjustTimer(-15)">−15s</button><button onclick="adjustTimer(15)">+15s</button><button onclick="skipTimer()">Skip</button></div></div>`}
function tickTimer(){if(!timer||currentPage!=='walk')return;const remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));const el=$('#timerPanel');if(el){const strong=el.querySelector('strong');if(strong)strong.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`}if(remaining===0&&!timer.done){timer.done=true;if(timer.interval){clearInterval(timer.interval);timer.interval=null}if(state.settings.vibrate&&navigator.vibrate)navigator.vibrate([250,120,250]);if(state.settings.sound)beep();document.body.classList.add('timer-flash');setTimeout(()=>document.body.classList.remove('timer-flash'),1600);toast('Rest complete — you’re up');}}
function beep(){try{const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=880;g.gain.value=.15;o.start();o.stop(ctx.currentTime+.25)}catch(e){}}
function confirmExit(){overlay.innerHTML=`<div class="drawer-backdrop"><section class="drawer modal-wrap"><h2>End this workout?</h2><p class="muted">Your completed sets can still be saved to history.</p><div class="modal-actions"><button class="primary full" onclick="finishWorkout()">Finish and save</button><button class="ghost full" onclick="closeOverlay()">Keep training</button></div></section></div>`}
function finishWorkout(){closeOverlay();if(sessionClock)clearInterval(sessionClock);sessionClock=null;if(timer?.interval)clearInterval(timer.interval);timer=null;workout.elapsed=Math.max(1,Math.round((Date.now()-workout.start)/60000));const minutes=workout.elapsed;const exercises=workout.exercises.map((e,i)=>({id:e.id,name:state.swaps[e.id]||e.name,sets:workout.values[i].map((v,j)=>({...v,done:workout.done[i].includes(j)}))}));const session={date:new Date().toISOString(),day:days[workout.day].title,minutes,exercises};state.history.push(session);save();const totalSets=exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).length,0),volume=exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).reduce((a,s)=>a+(+s.weight||0)*(+s.reps||0),0),0);workout=null;currentPage='finish';$('.bottom-nav').classList.remove('hidden');app.innerHTML=`<div class="container"><section class="workout-card"><div class="eyebrow">SESSION COMPLETE</div><h1>Good work.<br>That’s in the books.</h1><p class="muted">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})} · ${days[selectedDay].title}</p><div class="grid2"><div class="small-card"><b>${totalSets}</b><span>sets completed</span></div><div class="small-card"><b>${Math.round(volume).toLocaleString()} kg</b><span>volume logged</span></div><div class="small-card"><b>${minutes} min</b><span>session duration</span></div><div class="small-card"><b>${prCount(session)}</b><span>new PRs</span></div></div><p class="cue">Next time: if you hit the top of the rep range on every set, add the smallest weight jump.</p><button class="primary full" onclick="showHome()">Back to week</button><button class="secondary full" style="margin-top:8px" onclick="showHistory()">See progress</button></section></div>`}
function prCount(session){return session.exercises.reduce((n,e)=>{const best=Math.max(0,...(e.sets||[]).filter(s=>s.done).map(s=>+s.weight||0));const old=Math.max(0,...state.history.slice(0,-1).flatMap(x=>x.exercises||[]).filter(x=>x.id===e.id).flatMap(x=>x.sets||[]).filter(s=>s.done).map(s=>+s.weight||0));return n+(best>old&&best>0?1:0)},0)}
function showHistory(){currentPage='history';$('.bottom-nav').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===1));const options=window.WORKOUT_DATA.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');app.innerHTML=`<div class="container"><div class="eyebrow">YOUR TRAINING LOG</div><h1>Progress</h1><section class="card"><div class="workout-head"><h2>Top set over time</h2><select id="chartExercise" onchange="drawChart()" style="background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:9px;padding:8px;max-width:52%">${options}</select></div><div class="chart-wrap"><svg class="chart" id="chart" viewBox="0 0 600 180" role="img" aria-label="Top set weight chart"></svg></div><span class="muted" style="font-size:11px">Weight (kg) · best logged set per session</span></section><div class="section-title"><h2>Bodyweight</h2><button class="secondary" onclick="logBodyweight()">+ Log weight</button></div><section class="card"><svg id="bodychart" class="chart" viewBox="0 0 600 130"></svg><div class="muted">Optional trend · kg</div></section><div class="section-title"><h2>Past sessions</h2><button class="secondary" onclick="exportData()">Export JSON</button></div><section class="card">${state.history.length?state.history.slice().reverse().map(s=>`<div class="session-row"><span><b>${esc(s.day)}</b><br><small class="muted">${new Date(s.date).toLocaleDateString()} · ${s.minutes||0} min</small></span><span>${s.exercises.reduce((n,e)=>n+e.sets.filter(x=>x.done).length,0)} sets</span></div>`).join(''):'<p class="muted">Sessions you complete will appear here.</p>'}</section><div class="section-title"><h2>Data</h2></div><div class="grid2"><button class="secondary" onclick="importFile.click()">Import JSON</button><button class="secondary" onclick="resetData()">Reset all data</button><input id="importFile" class="hidden" type="file" accept="application/json" onchange="importData(this.files[0])"></div></div>`;drawChart();drawBodyChart()}
function drawChart(){const id=$('#chartExercise')?.value||window.WORKOUT_DATA[0].id;const points=[];state.history.forEach(s=>s.exercises?.filter(e=>e.id===id).forEach(e=>{const sets=e.sets.filter(x=>x.done&&+x.weight>0);if(sets.length)points.push({date:new Date(s.date),weight:Math.max(...sets.map(x=>+x.weight))})}));const svg=$('#chart');if(!svg)return;const w=600,h=180,p=30;svg.innerHTML='<path d="M30 15V150H580" fill="none" stroke="var(--line)"/>'+[0,1,2,3].map(i=>`<path d="M30 ${25+i*40}H580" stroke="var(--line)" stroke-dasharray="3 5"/>`).join('');if(points.length){let max=Math.max(...points.map(x=>x.weight)),min=Math.min(...points.map(x=>x.weight));if(max===min)min=Math.max(0,min-5);let coords=points.map((x,i)=>[p+(points.length===1?270:i*(w-2*p)/(points.length-1)),145-(x.weight-min)/(max-min)*110]);svg.innerHTML+=`<polyline points="${coords.map(c=>c.join(',')).join(' ')}" fill="none" stroke="var(--accent2)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`+coords.map((c,i)=>`<circle cx="${c[0]}" cy="${c[1]}" r="5" fill="var(--accent)"/><text x="${c[0]}" y="${c[1]-12}" text-anchor="middle" fill="var(--muted)" font-size="12">${points[i].weight}</text>`).join('')}else svg.innerHTML+='<text x="300" y="90" text-anchor="middle" fill="var(--muted)" font-size="14">Log sets with a weight to see your trend</text>'}
function logBodyweight(){const v=prompt('Bodyweight in kg');if(!v||!Number.isFinite(+v))return;state.bodyweight.push({date:new Date().toISOString(),weight:+v});save();showHistory()}
function drawBodyChart(){const svg=$('#bodychart');if(!svg)return;const p=state.bodyweight;if(!p.length){svg.innerHTML='<text x="300" y="68" text-anchor="middle" fill="var(--muted)" font-size="14">Add a bodyweight entry to start your trend</text>';return}let lo=Math.min(...p.map(x=>x.weight)),hi=Math.max(...p.map(x=>x.weight));if(lo===hi){lo-=1;hi+=1}let c=p.map((x,i)=>[30+(i/(Math.max(1,p.length-1)))*540,100-(x.weight-lo)/(hi-lo)*70]);svg.innerHTML=`<polyline points="${c.map(x=>x.join(',')).join(' ')}" fill="none" stroke="var(--accent2)" stroke-width="4"/>`}
function openSettings(){currentPage='settings';$('.bottom-nav').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===2));app.innerHTML=`<div class="container"><div class="eyebrow">PREFERENCES</div><h1>Settings</h1><section class="card"><h2>Workout</h2>${settingRow('Sound on rest timer','sound')}${settingRow('Vibrate on rest timer','vibrate')}${settingRow('Auto-start rest timer','autoStart')}<div class="fields"><label>Language<select onchange="setLanguage(this.value)"><option value="en" ${state.settings.language==='en'?'selected':''}>English</option><option value="fr" ${state.settings.language==='fr'?'selected':''}>Français</option></select></label><label>Theme<select onchange="setTheme(this.value)"><option value="dark">Dark</option><option value="light" ${state.settings.theme==='light'?'selected':''}>Light</option><option value="system">System</option></select></label></div></section><section class="card" style="margin-top:14px"><h2>Data portability</h2><p class="muted">Your workouts stay on this device.</p><div class="grid2"><button class="secondary" onclick="exportData()">Export JSON</button><button class="secondary" onclick="$('#importFileSettings').click()">Import JSON</button><input id="importFileSettings" class="hidden" type="file" accept="application/json" onchange="importData(this.files[0])"></div><button class="ghost full" style="margin-top:12px" onclick="resetData()">Reset all data</button></section><section class="card" style="margin-top:14px"><h2>Deload check-in</h2><p class="muted">Every six weeks, consider a lighter week with less volume and comfortable effort. You have logged ${state.history.length} sessions.</p></section></div>`;applyTheme()}
function settingRow(label,key){return `<label class="checkline">${label}<input class="toggle" type="checkbox" ${state.settings[key]?'checked':''} onchange="state.settings.${key}=this.checked;save()"></label>`}
function setTheme(v){state.settings.theme=v;save();applyTheme()}function applyTheme(){let t=state.settings.theme;if(t==='system')t=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.documentElement.dataset.theme=t}
function toggleTheme(){state.settings.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';save();applyTheme();if(currentPage==='home')renderHome()}
function setLanguage(v){state.settings.language=v;document.documentElement.lang=v;save();if(currentPage==='home')renderHome();else if(currentPage==='history')showHistory();else if(currentPage==='settings')openSettings();else if(currentPage==='walk')renderWalk();updateNavLanguage(v);if(v==='fr')translatePage();toast(v==='fr'?'Langue enregistrée':'Language saved')}
function updateNavLanguage(language){const nav=document.querySelectorAll('.bottom-nav button'),labels=language==='fr'?['Aujourd’hui','Progrès','Paramètres']:['Today','Progress','Settings'];nav.forEach((b,i)=>{const text=[...b.childNodes].find(x=>x.nodeType===Node.TEXT_NODE);if(text)text.nodeValue=' '+labels[i]})}
function translatePage(){if(state.settings.language!=='fr')return;const dict={'Today':'Aujourd’hui','Progress':'Progrès','Settings':'Paramètres','Your week,':'Votre semaine,','one rep at a time.':'une répétition à la fois.','Five sessions. Two lower days. Room to grow.':'Cinq séances ciblées. Du temps pour récupérer.','Keep the streak easy':'Restez régulier sans forcer','Next deload':'Prochain allègement','Recent sessions':'Séances récentes','Start workout':'Démarrer la séance','Quick warm-up':'Échauffement rapide','A little preparation helps you move well through the first working set.':'Préparez-vous avant votre première série de travail.','5 minutes of easy cardio':'5 minutes de cardio léger','1–2 ramp-up sets before the first lift':'1 à 2 séries de montée en charge','Let’s train':'On commence','Not now':'Pas maintenant','Working sets':'Séries de travail','Exercise tools':'Outils de l’exercice','TAP A CIRCLE WHEN DONE':'Touchez un cercle après la série','YOUR KEY CUE':'REPÈRE TECHNIQUE','HOW TO':'CONSIGNES','No previous set logged':'Aucune série précédente','Back':'Retour','Next exercise':'Exercice suivant','Finish workout':'Terminer la séance','Swap exercise':'Changer d’exercice','Form videos':'Vidéos de démonstration','Workout overview':'Aperçu de la séance','Close':'Fermer','Top set over time':'Charge maximale par séance','Past sessions':'Séances précédentes','Bodyweight':'Poids corporel','Export JSON':'Exporter les données JSON','Import JSON':'Importer des données JSON','Reset all data':'Réinitialiser les données','Sound on rest timer':'Son du minuteur','Vibrate on rest timer':'Vibration du minuteur','Auto-start rest timer':'Démarrer le repos automatiquement','Language':'Langue','Theme':'Thème','Dark':'Sombre','Light':'Clair','System':'Système','Data portability':'Sauvegarde des données','Deload check-in':'Rappel d’allègement'};const walker=document.createTreeWalker(app,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const trimmed=n.nodeValue.trim();if(dict[trimmed])n.nodeValue=n.nodeValue.replace(trimmed,dict[trimmed])}const nav=document.querySelectorAll('.bottom-nav button');nav.forEach((b,i)=>{const t=['Aujourd’hui','Progrès','Paramètres'][i],text=[...b.childNodes].find(x=>x.nodeType===Node.TEXT_NODE);if(text)text.nodeValue=' '+t})}
let translationDelay;new MutationObserver(()=>{if(state.settings.language!=='fr')return;clearTimeout(translationDelay);translationDelay=setTimeout(translatePage,250)}).observe(app,{childList:true,subtree:true,characterData:true});
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chax-training-data.json';a.click();URL.revokeObjectURL(a.href)}
async function importData(file){if(!file)return;try{let d=JSON.parse(await file.text());if(!d||typeof d!=='object')throw Error();state={...defaults,...d,settings:{...defaults.settings,...d.settings}};save();toast('Data imported');showHistory()}catch(e){toast('That file is not valid workout data')}}
function resetData(){if(confirm('Reset all workout history, settings, swaps, and bodyweight data?')){try{localStorage.removeItem('iron-data')}catch(e){}state=structuredClone(defaults);document.documentElement.lang='en';save();updateNavLanguage('en');toast('All data reset');showHome()}}
function closeOverlay(){overlay.innerHTML=''}function toast(msg){const t=$('#toast');t.textContent=msg;t.className='toast show';setTimeout(()=>t.className='toast',1900)}
let touchX=0;app.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX},{passive:true});app.addEventListener('touchend',e=>{if(currentPage!=='walk')return;const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>75)step(d<0?1:-1)},{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&timer)tickTimer();if(!document.hidden&&workout&&!wake&&'wakeLock'in navigator)navigator.wakeLock.request('screen').then(x=>wake=x).catch(()=>{})});
document.documentElement.lang=state.settings.language;applyTheme();showHome();window.setTimeout(dismissSplash,950);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=13').catch(()=>{}));

function dismissSplash(){const splash=$('#splash');if(!splash||splash.dataset.dismissed)return;splash.dataset.dismissed='true';splash.classList.add('is-leaving');window.setTimeout(()=>splash.remove(),280)}
